name: 10-Re-Entrancy
plugins:
  - name: solidity
  - name: alchemy
  - name: foundry
default_ecosystem: ethereum
ethereum:
  default_network: sepolia-fork
  sepolia:
    default_provider: alchemy
  sepolia_fork:
    default_provider: foundry
    default_transaction_type: 0
    transaction_acceptance_timeout: 600 # 5 minutes
foundry:
  fork:
    ethereum:
      sepolia_fork:
        upstream_provider: alchemy

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 3.2.0
  
solidity:
  import_remapping:
    - "openzeppelin-contracts-06=OpenZeppelin/3.2.0"
