[tool.poetry]
name = "06-Delegation"
version = "0.1.0"
description = ""
authors = ["Saikat K <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
eth-ape = "^0.7.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
