name: simple_storage
plugins:
  - name: solidity
    version: 0.6.3 # version of the plugin
  - name: ganache
  - name: alchemy
  - name: hardhat
  # - name: ens
  # - name: etherscan
ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: ganache
ganache:
  server:
    port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
